# Generated by Django 5.1.3 on 2024-11-08 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8)),
                ('valor', models.FloatField()),
                ('cota_qtd', models.IntegerField()),
                ('dividendos', models.FloatField(blank=True, null=True)),
                ('dividendo_total', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['id', 'name'],
            },
        ),
    ]
