# Generated by Django 5.1.3 on 2024-11-09 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fill', '0003_remove_calculadividendos_fill_fill_fill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fill',
            name='fill',
        ),
        migrations.AddField(
            model_name='calculadividendos',
            name='fill',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Fill.fill'),
            preserve_default=False,
        ),
    ]
