# Generated by Django 5.1.3 on 2024-11-09 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fill', '0004_remove_fill_fill_calculadividendos_fill'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CalculaDividendos',
            new_name='CalculaDividendo',
        ),
    ]
