# Generated by Django 5.1.3 on 2024-11-27 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fill', '0006_fill_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='fill',
            name='dividendo_total',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='CalculaDividendo',
        ),
    ]
